export const products = [
  {
    id: 1,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/1.jpeg",
  },
  {
    id: 2,
    name: "Decorative Ceiling Fan",
    description: "Premium design for modern interiors",
    price: 3200,
    oldPrice: 4200,
    rating: 4,
    image: "/2.jpeg",
  },
  {
    id: 3,
    name: "Industrial Exhaust Fan",
    description: "Heavy-duty ventilation solution",
    price: 1800,
    oldPrice: 2500,
    rating: 4,
    image: "/3.jpeg",
  },
  {
    id: 4,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/4.jpeg",
  },
  {
    id: 5,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/5.jpeg",
  },
  {
    id: 6,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/6.jpeg",
  },
  {
    id: 7,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/7.jpeg",
  },
  {
    id: 8,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/8.jpeg",
  },
  {
    id: 9,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/9.jpeg",
  },
  {
    id: 10,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/10.jpeg",
  },
  {
    id: 11,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/11.jpeg",
  },
  {
    id: 12,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/12.jpeg",
  },
  {
    id: 13,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/13.jpeg",
  },
  {
    id: 14,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/14.jpeg",
  },
  {
    id: 15,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/15.jpeg",
  },
  {
    id: 16,
    name: "High Speed Ceiling Fan",
    description: "Energy efficient fan with high air delivery",
    price: 2456,
    oldPrice: 3500,
    rating: 5,
    image: "/16.jpeg",
  },
];
